checks:
    php: true

build:
    dependencies:
        override:
            - { command: 'mkdir -p app/etc && rm -rf ./vendor/ && composer install --no-interaction', idle_timeout: 600 }
    tests:
        override:
            - phpcs-run --config-set installed_paths /home/scrutinizer/build/vendor/magento/marketplace-eqp/
            - phpcs-run --standard=MEQP2 --ignore=./vendor/ ./
    cache:
        directories: [ ~/.composer/cache ]

tools:
    external_code_coverage:
        timeout: 600
        runs: 2
